language: erlang
otp_release: 20.2
before_script:
    - sudo apt install erlang-proper-dev
    - export ERL_LIBS=/usr/lib/erlang/lib/proper-1.1
script: rebar3 compile && rebar3 do ct,cover && rebar3 as test coveralls send
